name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Build application
        run: npm run build

      - name: Upload artifacts to Azure Storage
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az storage blob upload-batch \
              --account-name <your-storage-account-name> \
              --account-key ${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }} \
              --destination <container-name> \
              --source ./build # Replace with your build output folder

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifacts from Azure Storage
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az storage blob download-batch \
              --account-name <your-storage-account-name> \
              --account-key ${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }} \
              --source <container-name> \
              --destination ./downloaded-artifacts

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: "your-app-service-name" # Replace with your Azure App Service name
          slot-name: "production"          # Optional: Specify the deployment slot (default is production)
          package: ./downloaded-artifacts # Path to the downloaded artifacts